Onboarding
edge/cli pull request #43
Opened 2021-11-24 17:09 UTC by annybs

This PR includes all basic device commands covering the full onboarding journey:

- Add device to network (initialize & assign to stake)
- Show device and stake info
- Start/restart/stop node corresponding to stake type - host, gateway, stargate
- Show status of node, i.e. whether it is running or not

There is also 'offboarding' capability via `device remove` to remove the device from the network:

- Unassign stake
- Stop node (if running)
- Delete device info

This closes multiple issues, which will link back to this PR.

2021-11-24 17:09 UTC, annybs commented
This PR is a draft at the moment because there are multiple UX issues, as I will discuss on #19 

However, the basic functions are present and correct and available to check over now if desired.

2021-11-26 14:23 UTC, adamkdean requested changes
Generally LGTM. Try to remember to add in the required header comments to new files. Official memo messages should always be Uppercase Every First Character.

2021-11-26 14:23 UTC, adamkdean commented on .build/Dockerfile
> +FROM node:14
Insert above L1:

```
# Copyright (C) 2021 Edge Network Technologies Limited
# Use of this source code is governed by a GNU GPL-style license
# that can be found in the LICENSE.md file. All rights reserved.
```

2021-11-26 14:23 UTC, adamkdean commented on .build/auto_target.sh
> +#!/bin/bash
Insert after hashbang, like so:

```
#!/bin/bash
# Copyright (C) 2021 Edge Network Technologies Limited
# Use of this source code is governed by a GNU GPL-style license
# that can be found in the LICENSE.md file. All rights reserved.

set -e
```

2021-11-26 14:23 UTC, adamkdean commented on .build/build.sh
> +#/bin/bash
Invalid hashbang. Also, insert comment, leaving line after, like so:

```
#!/bin/bash
# Copyright (C) 2021 Edge Network Technologies Limited
# Use of this source code is governed by a GNU GPL-style license
# that can be found in the LICENSE.md file. All rights reserved.

set -e
```

2021-11-26 14:23 UTC, adamkdean commented on package.json
> +    "@types/tar-stream": "^2.2.2",
`@types/tar-stream` should be dev dep

2021-11-26 14:23 UTC, adamkdean commented on src/device/cli.ts
> +  'run a node of the staked type.\n\n',
staked type -> stake type? 

Not sure on this. Thoughts?

2021-11-26 14:23 UTC, adamkdean commented on src/device/cli.ts
> +        memo: 'Unassign device from stake',
As per brand guidelines, this should be title case. I recommend the memo `Unassign Device`.

2021-11-26 14:23 UTC, adamkdean commented on src/device/cli.ts
> +      memo: 'Assign device to stake',
Change to `Assign Device`

2021-11-26 14:23 UTC, adamkdean commented on src/device/data.ts
> +import * as xe from '@edge/xe-utils'
Prepend with 

```
// Copyright (C) 2021 Edge Network Technologies Limited
// Use of this source code is governed by a GNU GPL-style license
// that can be found in the LICENSE.md file. All rights reserved.
```

2021-11-26 14:23 UTC, adamkdean commented on src/device/data.ts
> +import * as xe from '@edge/xe-utils'
P.S. always leave a line after these header comments

2021-11-26 14:23 UTC, adamkdean commented on src/device/node.ts
> +import * as data from './data'
Prepend with

```
// Copyright (C) 2021 Edge Network Technologies Limited
// Use of this source code is governed by a GNU GPL-style license
// that can be found in the LICENSE.md file. All rights reserved.
```

2021-11-26 14:23 UTC, adamkdean commented on src/stake/cli.ts
> +  const vars = await xe.vars(network.blockchain.baseURL)
Ensure that if this fails for any reason, a message is displayed informing the user that staking is currently unavailable and to try back later

2021-11-26 14:23 UTC, adamkdean commented on src/stake/cli.ts
> +  'This command will create a stake in the blockchain.\n\n',
_on_ the blockchain

2021-11-26 14:23 UTC, adamkdean commented on src/stake/index.ts
> +import * as xe from '@edge/xe-utils'
Prepend with

```
// Copyright (C) 2021 Edge Network Technologies Limited
// Use of this source code is governed by a GNU GPL-style license
// that can be found in the LICENSE.md file. All rights reserved.
```

2021-11-26 14:55 UTC, annybs commented on package.json
> +    "@types/tar-stream": "^2.2.2",
Good catch!

2021-11-26 15:14 UTC, adamkdean submitted a review, later dismissed

2021-11-26 15:14 UTC, adamkdean commented
LGTM, do you want to bump the version before you merge this?

2021-11-26 15:15 UTC, adamkdean commented
`v1.1.0` 🎉

2021-11-26 15:22 UTC, adamkdean approved these changes
![image](https://user-images.githubusercontent.com/1639527/143602285-d1015048-b539-49f0-b33f-b5d35cfd28a4.png)

2021-11-26 15:23 UTC, merged

2021-11-26 15:23 UTC, annybs commented
Yes!